# Generated by Django 3.0.6 on 2020-06-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200, verbose_name='firstName')),
                ('last_name', models.CharField(max_length=200, verbose_name='lastName')),
                ('slug', models.SlugField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams_logo/')),
                ('jersey_number', models.IntegerField()),
                ('country', models.CharField(max_length=100, verbose_name='country')),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
    ]
