# Generated by Django 3.0.6 on 2020-06-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200530_0126'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='team_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.Teams', verbose_name='Team'),
        ),
    ]
