# Generated by Django 3.0.6 on 2020-06-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_players_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('player_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('matches', models.IntegerField()),
                ('run', models.IntegerField()),
                ('highest_score', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('hundred', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Players')),
            ],
        ),
    ]
