# Generated by Django 3.0.6 on 2020-06-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_playerhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerhistory',
            options={'verbose_name_plural': 'Player History'},
        ),
    ]
