# Generated by Django 3.0.6 on 2020-06-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20200603_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
