# Generated by Django 3.0.6 on 2020-05-29 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('teams_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams_logo/')),
                ('club_state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='points',
            fields=[
                ('points_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_points', models.DecimalField(blank=True, decimal_places=2, help_text='Points', max_digits=10)),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Teams', to='teams.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MatchTeamOne', to=settings.AUTH_USER_MODEL)),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MatchTeamTwo', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
